#!/bin/bash
set -Eexuo pipefail

cd $(dirname $0)/..

docker volume create --name stack-global-debian > /dev/null

mkdir -p ./dist

docker-compose build ${SERVICE-dev}

docker-compose run --service-ports --rm ${SERVICE-dev} "$@"
