#!/bin/bash
set -Eexuo pipefail

cd $(dirname $0)/..

docker volume create --name stack-global > /dev/null

mkdir -p ./dist

docker-compose build ${SERVICE-dev}

docker-compose run --rm ${SERVICE-dev} "$@"
