#!/bin/bash
set -Eexuo pipefail

cd $(dirname $0)/..

# auto/build-to-local

docker build -t myregistry.com/servant-persistent:latest -f support/prod/Dockerfile .

exec docker run \
  -it myregistry.com/servant-persistent:latest
